inspirehep/inspire-utils

- inspire_utils/date.py
- setup.py
- tests/test_date.py
These utils are used to handle correctly partial dates, lacking day or
month parts.
Signed-off-by: Micha Moskovic <michamos@gmail.com>
> date: add module

- inspire_utils/helpers.py
- setup.py
- tests/test_helpers.py
Signed-off-by: Micha Moskovic <michamos@gmail.com>
> helpers: add remove_tags util

- inspire_utils/helpers.py
- tests/test_helpers.py
Signed-off-by: Micha Moskovic <michamos@gmail.com>
> helpers: remove_tags keeps tails of stripped tags

- inspire_utils/helpers.py
- tests/test_helpers.py
Signed-off-by: Micha Moskovic <michamos@gmail.com>
> helpers: remove_tags keeps text of allowed_tags

- inspire_utils/name.py
- tests/test_name.py
Signed-off-by: Chris Aslanoglou <chris.aslanoglou@gmail.com>
> name: capitalize name for single name variation

- inspire_utils/date.py
- inspire_utils/name.py
- setup.py
Prevents some errors while dealing with Unicode by adding the
``unicode-string-literal`` dependency, which adds an extra Flake8
check for Unicode-unsafe constructs.
> global: add the unicode-string-literal dependency

- setup.py
See: https://travis-ci.org/inspirehep/inspire-next/jobs/325792639#L911
> setup: bump Unidecode

- inspire_utils/name.py
- tests/test_name.py
Adds a `from_parts` method to ParsedName.
> name: assemble normalized name from parts

- .travis.yml
- run-tests.sh
- setup.py
Remove ``pytest-flake8`` and replace it with just ``flake8`` as the
former is sometimes not finding style violations present in the code.
> global: don't use pytest-flake8

- inspire_utils/config.py
- tests/test_config.py
Signed-off-by: Szymon Łopaciuk <szymon.lopaciuk@cern.ch>
> create a config loader similar to flask one

- inspire_utils/name.py
- tests/test_name.py
Signed-off-by: Iuliana Voinea <iulianavoinea96@gmail.com>
> name: take all last names as variations

- inspire_utils/name.py
- tests/test_name.py
Signed-off-by: Victor Balbuena <vbalbp@gmail.com>
> name: correctly format multiple middle names

- inspire_utils/name.py
- tests/test_name.py
Signed-off-by: Victor Balbuena <vbalbp@gmail.com>
> name: add new formatting function

- inspire_utils/name.py
- tests/test_name.py
Signed-off-by: Victor Balbuena <vbalbp@gmail.com>
> name: correctly format name with suffixes

- inspire_utils/name.py
- tests/test_name.py
Signed-off-by: Victor Balbuena <vbalbp@gmail.com>
> name: treat single name as last name in pprint

- inspire_utils/record.py
- tests/test_record.py
> record: allow get_value on lists

- inspire_utils/date.py
- tests/test_date.py
Adds default_day and default_month for earliest_date, so when day or month will be missing then adds default value so date will be complete
> Add default values for earliest_date

- inspire_utils/date.py
- tests/test_date.py
Signed-off-by: Antonio Cesarano <cesarano2607@gmail.com>
> date: stop using ISO week date format

- .travis.yml
- setup.py
Update lxml package to 4.4.x which is comaptible with python 3.8
> add support for py3.8

- inspire_utils/name.py
- tests/test_name.py
> names: correctly generate initials for composite names

- inspire_utils/name.py
- tests/test_name.py
* INSPIR-3477
* fix wrong display of facet_author_name in inspire from previous update
> names: correctly generate initials and display composite names

- inspire_utils/dedupers.py
- inspire_utils/name.py
- setup.py
- tests/test_name.py
> names: show initials not separated by whitespace

- inspire_utils/name.py
- tests/test_name.py
> names: regression when only one name with comma

- inspire_utils/name.py
- tests/test_name.py
Ref: https://github.com/inspirehep/inspirehep/issues/2174
> name-normalization: add title to first name when first is empty

- inspire_utils/date.py
- tests/test_date.py
> date: don't validate 00 as a day

- inspire_utils/name.py
- tests/test_name.py
Ref: https://github.com/cern-sis/issues-inspire/issues/53
> fix Ed is stripped in LaTeX formats

- inspire_utils/record.py
- setup.py
ref: cern-sis/issues-inspire#48
> move `normalize_affiliations` from next

- inspire_utils/record.py
https://github.com/cern-sis/issues-inspire/issues/48
> affiliation normalization: use search object instead of current_search

- inspire_utils/record.py
> aff normalization: add logging

- .github/workflows/build-and-publish.yml
- .github/workflows/bump.yml
- .github/workflows/test-python-3.yml
Update some action and os versions and set them to fixed version
> actions: update versions

- inspire_utils/parsers/author_xml.py
- setup.cfg
- setup.py
- tests/test_parsers_author_xml.py
* ref: https://github.com/cern-sis/issues-inspire/issues/427
> Add author xml

- .github/workflows/bump-and-publish.yml
- .github/workflows/test-python-2.yml
- inspire_utils/isbn.py
- setup.cfg
- setup.py
- tests/test_isbn.py
* ref https://github.com/cern-sis/issues-inspire/issues/902
> isbn: add normalize for isbn

- .github/workflows/bump-and-publish.yml
- .github/workflows/test-python-2.yml
- README.md
- inspire_utils/isbn.py
- tests/test_isbn.py
ref: https://github.com/cern-sis/issues-inspire/issues/1029
> 1029 ensure pep 625 compliant
